---
- name: Install docker
  become: true
  hosts: all
  tasks:

  - name: Install docker dependencies
    apt:
        name: "{{ item }}"
        state: present
    with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"
    - "cron"
    - "python-pip"
  - name: Add Docker apt key.
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
  - name: Add APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present
  - name: Install docker
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
    - "docker-ce"
    - "docker-compose"
  - name: pip install
    pip:
      name: docker-py
      extra_args: --upgrade

  - name: Prepare environment
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - /srv/gitlab/config
    - /srv/gitlab/data
    - /srv/gitlab/logs
  - name: Download docker-compose.yml from gist
    get_url: 
      url: https://gist.githubusercontent.com/Nklya/c2ca40a128758e2dc2244beb09caebe1/raw/e9ba646b06a597734f8dfc0789aae79bc43a7242/docker-compose.yml
      dest: /srv/gitlab
